Apply shfmt formatting

diff --git a/bin/pymac b/bin/pymac
--- a/bin/pymac
+++ b/bin/pymac
@@ -28,49 +28,50 @@ pymac_cmd() {
 
   while :; do
     case "$command" in
-      -h|help|--help|"")
-        help
-        break
-        ;;
-      certifi-update|default|exec|uninstall|update)
-        shift
-        # If Python version number provided, validate it
-        if [[ $1 =~ ^[0-9][.]* ]]; then
-          if py_valid "$1"; then
-            IFS='.' read -ra PYVERSION <<< "$1"
-            py_version="${PYVERSION[0]}.${PYVERSION[1]}"
-            if ! is_installed "$py_version"; then
-              printf "Python version %s not installed.\n" "$py_version"
-              return 1
-            fi
-            if [[ ${#PYVERSION[@]} -eq 3 ]]; then
-              printf "Calling 'pymac %s %s' instead (ignoring the Micro version you provided)\n" "$command" "$py_version"
-            fi
-          else
-            printf "Please provide a valid Python version number.\n"
+    -h | help | --help | "")
+      help
+      break
+      ;;
+    certifi-update | default | exec | uninstall | update)
+      shift
+      # If Python version number provided, validate it
+      if [[ $1 =~ ^[0-9][.]* ]]; then
+        if py_valid "$1"; then
+          IFS='.' read -ra PYVERSION <<<"$1"
+          py_version="${PYVERSION[0]}.${PYVERSION[1]}"
+          if ! is_installed "$py_version"; then
+            printf "Python version %s not installed.\n" "$py_version"
             return 1
           fi
-          shift
-        fi
-        # If Python version has been set, call command with it
-        if [[ -n "$py_version" ]]; then
-          # shellcheck disable=1090
-          . "$(pymac_dir)"/commands/"$command".bash "$py_version" "$@"
+          if [[ ${#PYVERSION[@]} -eq 3 ]]; then
+            printf "Calling 'pymac %s %s' instead (ignoring the Micro version you provided)\n" "$command" "$py_version"
+          fi
         else
-          # shellcheck disable=1090
-          . "$(pymac_dir)"/commands/"$command".bash "$@"
+          printf "Please provide a valid Python version number.\n"
+          return 1
         fi
-        break
-        ;;
-      clear-cache|default-which|install|list|pyenv|update-all|upgrade)
         shift
+      fi
+      # If Python version has been set, call command with it
+      if [[ -n "$py_version" ]]; then
+        # shellcheck disable=1090
+        . "$(pymac_dir)"/commands/"$command".bash "$py_version" "$@"
+      else
         # shellcheck disable=1090
         . "$(pymac_dir)"/commands/"$command".bash "$@"
-        break
-        ;;
-      *)
-        printf "Invalid command. See 'pymac help' for usage.\n"
-        break
+      fi
+      break
+      ;;
+    clear-cache | default-which | install | list | pyenv | update-all | upgrade)
+      shift
+      # shellcheck disable=1090
+      . "$(pymac_dir)"/commands/"$command".bash "$@"
+      break
+      ;;
+    *)
+      printf "Invalid command. See 'pymac help' for usage.\n"
+      break
+      ;;
     esac
   done
 }
